# -*- coding: utf-8 -*-
"""mean_difference_of_nth_root_error

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8epnfNTqt_HhXayNlTyoVE8onMWsUBN
"""

def md_nre_single_sample(y, y_hat, n, p):
    '''
    Calculates the Mean Difference of nth Root Error for a single sample

    Parameters:
    y: actual value
    y_hat: predicted value
    n: numbers of observations
    p: power of the loss function
    '''

    # Calculate nth root of y
    y_root = y ** (1/n)

    # Calculate nth root of y_hat
    y_hat_root = y_hat ** (1/n)

    # Calculate difference between y and y_hat after rooting
    difference = y_root - y_hat_root

    # Calculate the loss value
    loss = difference ** p

    return loss # Return the loss value
# Assertion of the function
assert md_nre_single_sample(y=100, y_hat=99.5, n=2, p=1) == 0.025031328369998107

# Print the function with some test values
print(md_nre_single_sample(y=50, y_hat=49.5, n=2, p=1))
print(md_nre_single_sample(y=20, y_hat=19.5, n=2, p=1))
print(md_nre_single_sample(y=0.6, y_hat=0.1, n=2, p=1))